// <auto-generated />
using System;
using AnthroCloud.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnthroCloud.Entities.Migrations
{
    [DbContext(typeof(AssessmentContext))]
    [Migration("20221014121351_AssessmentDb_Measures")]
    partial class AssessmentDb_Measures
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AnthroCloud.Entities.Measure", b =>
                {
                    b.Property<int>("MeasureId")
                        .HasColumnType("int");

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.Property<double>("Percentile")
                        .HasColumnType("float");

                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.Property<double>("Zscore")
                        .HasColumnType("float");

                    b.HasKey("MeasureId", "Name");

                    b.HasIndex("VisitId");

                    b.ToTable("Measures");
                });

            modelBuilder.Entity("AnthroCloud.Entities.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"), 1L, 1);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Sex")
                        .HasColumnType("tinyint");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            DateOfBirth = new DateTime(2021, 10, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            FirstName = "John",
                            LastName = "Smith",
                            Sex = (byte)0
                        },
                        new
                        {
                            PatientId = 2,
                            DateOfBirth = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            FirstName = "Juana",
                            LastName = "Diaz",
                            Sex = (byte)1
                        });
                });

            modelBuilder.Entity("AnthroCloud.Entities.Visit", b =>
                {
                    b.Property<int>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitId"), 1L, 1);

                    b.Property<DateTime>("DateOfVisit")
                        .HasColumnType("datetime2");

                    b.Property<double>("HeadCircumference")
                        .HasColumnType("float");

                    b.Property<double>("LengthHeight")
                        .HasColumnType("float");

                    b.Property<double>("MUAC")
                        .HasColumnType("float");

                    b.Property<int>("Measured")
                        .HasColumnType("int");

                    b.Property<byte>("Oedema")
                        .HasColumnType("tinyint");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<double>("SubscapularSkinFold")
                        .HasColumnType("float");

                    b.Property<double>("TricepsSkinFold")
                        .HasColumnType("float");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("VisitId");

                    b.HasIndex(new[] { "PatientId" }, "IX_Visits_PatientId");

                    b.ToTable("Visits");

                    b.HasData(
                        new
                        {
                            VisitId = 1,
                            DateOfVisit = new DateTime(2022, 1, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            HeadCircumference = 38.899999999999999,
                            LengthHeight = 18.0,
                            MUAC = 11.199999999999999,
                            Measured = 1,
                            Oedema = (byte)1,
                            PatientId = 1,
                            SubscapularSkinFold = 4.5999999999999996,
                            TricepsSkinFold = 5.5,
                            Weight = 16.0
                        },
                        new
                        {
                            VisitId = 2,
                            DateOfVisit = new DateTime(2022, 7, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            HeadCircumference = 40.299999999999997,
                            LengthHeight = 23.0,
                            MUAC = 11.4,
                            Measured = 1,
                            Oedema = (byte)0,
                            PatientId = 1,
                            SubscapularSkinFold = 4.4000000000000004,
                            TricepsSkinFold = 5.2000000000000002,
                            Weight = 20.0
                        },
                        new
                        {
                            VisitId = 3,
                            DateOfVisit = new DateTime(2021, 10, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            HeadCircumference = 41.600000000000001,
                            LengthHeight = 25.0,
                            MUAC = 11.5,
                            Measured = 1,
                            Oedema = (byte)1,
                            PatientId = 2,
                            SubscapularSkinFold = 4.0999999999999996,
                            TricepsSkinFold = 4.7999999999999998,
                            Weight = 26.0
                        },
                        new
                        {
                            VisitId = 4,
                            DateOfVisit = new DateTime(2021, 4, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            HeadCircumference = 42.700000000000003,
                            LengthHeight = 28.0,
                            MUAC = 11.6,
                            Measured = 1,
                            Oedema = (byte)1,
                            PatientId = 2,
                            SubscapularSkinFold = 3.8999999999999999,
                            TricepsSkinFold = 4.5,
                            Weight = 32.0
                        });
                });

            modelBuilder.Entity("AnthroCloud.Entities.Measure", b =>
                {
                    b.HasOne("AnthroCloud.Entities.Visit", null)
                        .WithMany("Measures")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnthroCloud.Entities.Visit", b =>
                {
                    b.HasOne("AnthroCloud.Entities.Patient", "Patient")
                        .WithMany("Visits")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("AnthroCloud.Entities.Patient", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("AnthroCloud.Entities.Visit", b =>
                {
                    b.Navigation("Measures");
                });
#pragma warning restore 612, 618
        }
    }
}
