#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

FROM mcr.microsoft.com/dotnet/core/aspnet:3.0-nanoserver-1903 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.0-nanoserver-1903 AS build
WORKDIR /src
COPY ["AnthroCloud/AnthroCloud.csproj", "AnthroCloud/"]
RUN dotnet restore "AnthroCloud/AnthroCloud.csproj"
COPY . .
WORKDIR "/src/AnthroCloud"
RUN dotnet build "AnthroCloud.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "AnthroCloud.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "AnthroCloud.dll"]